/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MartShopSystem;

import java.awt.Color;
import java.awt.GraphicsEnvironment;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author user
 */
public class ViewListPro extends javax.swing.JFrame {

    /**
     * @return the xx
     */
    public int getXx() {
        return xx;
    }

    /**
     * @param xx the xx to set
     */
    public void setXx(int xx) {
        this.xx = xx;
    }

    /**
     * @return the xy
     */
    public int getXy() {
        return xy;
    }

    /**
     * @param xy the xy to set
     */
    public void setXy(int xy) {
        this.xy = xy;
    }

    /**
     * @return the click
     */

    /**
     * Creates new form ViewListPro
     */
    public ViewListPro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SSeting = new javax.swing.JPanel();
        barHome = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        lbBack = new javax.swing.JLabel();
        txtSearch = new subjtextfiledsk15.SubJTextField();
        jLabel46 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new subjtable.SubJTable();
        pnlToolBar = new javax.swing.JPanel();
        cmdMin = new javax.swing.JButton();
        cmdMax = new javax.swing.JButton();
        cmdExit = new javax.swing.JButton();
        cmdDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        SSeting.setBackground(new java.awt.Color(247, 247, 247));

        barHome.setBackground(new java.awt.Color(255, 255, 255));
        barHome.setPreferredSize(new java.awt.Dimension(5, 5));
        barHome.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barHomeMouseDragged(evt);
            }
        });
        barHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barHomeMousePressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(98, 83, 150));
        jLabel8.setText("View List Product/Fee");

        jLabel45.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(98, 83, 150));
        jLabel45.setText("Status");

        jPanel8.setBackground(new java.awt.Color(98, 83, 150));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(181, 77, 180));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        lbBack.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbBack.setForeground(new java.awt.Color(98, 83, 150));
        lbBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Back_60px.png"))); // NOI18N
        lbBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBackMouseClicked(evt);
            }
        });

        txtSearch.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jLabel46.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(98, 83, 150));
        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconbarCube/icons8-search-32.png"))); // NOI18N

        javax.swing.GroupLayout barHomeLayout = new javax.swing.GroupLayout(barHome);
        barHome.setLayout(barHomeLayout);
        barHomeLayout.setHorizontalGroup(
            barHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barHomeLayout.createSequentialGroup()
                .addGroup(barHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(barHomeLayout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(lbBack, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(barHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(barHomeLayout.createSequentialGroup()
                                .addComponent(jLabel45)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(barHomeLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 720, Short.MAX_VALUE)
                                .addComponent(jLabel46)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(barHomeLayout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        barHomeLayout.setVerticalGroup(
            barHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barHomeLayout.createSequentialGroup()
                .addGroup(barHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(barHomeLayout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(barHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(barHomeLayout.createSequentialGroup()
                                .addGroup(barHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel46)
                                    .addGroup(barHomeLayout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(jLabel8)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel45))
                            .addComponent(lbBack, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jScrollPane1.setBackground(new java.awt.Color(247, 247, 247));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        table.setBackground(new java.awt.Color(247, 247, 247));
        table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Barcode", "Name", "Supplier", "Category", "Quality", "UPriceIn", "UPriceOut", "Status", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setColorSelected(new java.awt.Color(232, 201, 232));
        table.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(table);

        pnlToolBar.setBackground(new java.awt.Color(51, 51, 51));
        pnlToolBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlToolBarMouseDragged(evt);
            }
        });
        pnlToolBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlToolBarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlToolBarMouseReleased(evt);
            }
        });

        cmdMin.setBackground(new java.awt.Color(51, 51, 51));
        cmdMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconSwingUI/Minimize.png"))); // NOI18N
        cmdMin.setContentAreaFilled(false);
        cmdMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmdMin.setFocusable(false);
        cmdMin.setOpaque(true);
        cmdMin.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconSwingUI/Minimize (2).png"))); // NOI18N
        cmdMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmdMinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmdMinMouseExited(evt);
            }
        });
        cmdMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMinActionPerformed(evt);
            }
        });

        cmdMax.setBackground(new java.awt.Color(51, 51, 51));
        cmdMax.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconSwingUI/Maximize.png"))); // NOI18N
        cmdMax.setContentAreaFilled(false);
        cmdMax.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmdMax.setFocusable(false);
        cmdMax.setOpaque(true);
        cmdMax.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconSwingUI/Maximize (2).png"))); // NOI18N
        cmdMax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmdMaxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmdMaxMouseExited(evt);
            }
        });
        cmdMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMaxActionPerformed(evt);
            }
        });

        cmdExit.setBackground(new java.awt.Color(51, 51, 51));
        cmdExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconSwingUI/Exit.png"))); // NOI18N
        cmdExit.setContentAreaFilled(false);
        cmdExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmdExit.setFocusable(false);
        cmdExit.setOpaque(true);
        cmdExit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconSwingUI/Exit (2).png"))); // NOI18N
        cmdExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmdExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmdExitMouseExited(evt);
            }
        });
        cmdExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlToolBarLayout = new javax.swing.GroupLayout(pnlToolBar);
        pnlToolBar.setLayout(pnlToolBarLayout);
        pnlToolBarLayout.setHorizontalGroup(
            pnlToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlToolBarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cmdMin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdMax)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdExit))
        );
        pnlToolBarLayout.setVerticalGroup(
            pnlToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cmdExit, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
            .addComponent(cmdMax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cmdMin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        cmdDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmdDelete.setForeground(new java.awt.Color(181, 77, 180));
        cmdDelete.setText("Delete");
        cmdDelete.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(181, 77, 180)));
        cmdDelete.setContentAreaFilled(false);
        cmdDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmdDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdDelete.setOpaque(true);
        cmdDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SSetingLayout = new javax.swing.GroupLayout(SSeting);
        SSeting.setLayout(SSetingLayout);
        SSetingLayout.setHorizontalGroup(
            SSetingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(barHome, javax.swing.GroupLayout.DEFAULT_SIZE, 1370, Short.MAX_VALUE)
            .addGroup(SSetingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SSetingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SSetingLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cmdDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        SSetingLayout.setVerticalGroup(
            SSetingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SSetingLayout.createSequentialGroup()
                .addComponent(pnlToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(barHome, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SSeting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SSeting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1370, 696));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    static boolean maximized=true;
    private int xx,xy;
    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        try{
            Statement s=DataCon.getDataCon().createStatement();
            String search=txtSearch.getText();
            ResultSet r=s.executeQuery("select * from tblproduct where barcode like '"+search+"%' or proname like '"+search+"%'");
            if(r.first()){
                DefaultTableModel mod=(DefaultTableModel)table.getModel();
                TableRowSorter<DefaultTableModel> tr= new TableRowSorter<DefaultTableModel>(mod);
                table.setRowSorter(tr);
                tr.setRowFilter(RowFilter.regexFilter(search));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchKeyReleased

    private void barHomeMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barHomeMouseDragged
        try{
            int x=evt.getXOnScreen();
            int y=evt.getYOnScreen();
            this.setLocation(x-getXx(), y-getXy());
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_barHomeMouseDragged

    private void barHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barHomeMousePressed
        try{
            setXx(evt.getX());
            setXy(evt.getY());
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_barHomeMousePressed

    private void cmdMinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdMinMouseEntered
        try{
            cmdMin.setBackground(new Color(229,229,229));
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdMinMouseEntered

    private void cmdMinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdMinMouseExited
        try{
            cmdMin.setBackground(new Color(51,51,51));
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdMinMouseExited

    private void cmdMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMinActionPerformed
        try{
            this.setState(JFrame.ICONIFIED);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdMinActionPerformed

    private void cmdMaxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdMaxMouseEntered
        try{
            cmdMax.setBackground(new Color(229,229,229));
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdMaxMouseEntered

    private void cmdMaxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdMaxMouseExited
        try{
            cmdMax.setBackground(new Color(51,51,51));
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdMaxMouseExited

    private void cmdMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMaxActionPerformed
        try{
            if(maximized){
                ViewListPro.this.setExtendedState(JFrame.MAXIMIZED_BOTH);
                GraphicsEnvironment env=GraphicsEnvironment.getLocalGraphicsEnvironment();
                ViewListPro.this.setMaximizedBounds(env.getMaximumWindowBounds());
                maximized=false;
            }else{
                setExtendedState(JFrame.NORMAL);
                maximized=true;
            }
        }catch(Exception e){
            JOptionPane.showConfirmDialog(this, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdMaxActionPerformed

    private void cmdExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdExitMouseEntered
        try{
            cmdExit.setBackground(new Color(232,17,35));
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdExitMouseEntered

    private void cmdExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdExitMouseExited
        try{
            cmdExit.setBackground(new Color(51,51,51));
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdExitMouseExited

    private void cmdExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdExitActionPerformed
        try{
            System.exit(0);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdExitActionPerformed

    private void pnlToolBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlToolBarMouseDragged
        try{
            int x=evt.getXOnScreen();
            int y=evt.getYOnScreen();
            this.setLocation(x-getXx(), y-getXy());
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlToolBarMouseDragged

    private void pnlToolBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlToolBarMousePressed
        try{
            setOpacity((float)0.8);
            setXx(evt.getX());
            setXy(evt.getY());
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlToolBarMousePressed

    private void pnlToolBarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlToolBarMouseReleased
        try{
            setOpacity((float)1.0);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlToolBarMouseReleased

    private void cmdDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDeleteActionPerformed
        if(!table.getSelectionModel().isSelectionEmpty()){
            int Click=JOptionPane.showConfirmDialog(this, "Are you sure?","Confirm",JOptionPane.YES_NO_OPTION);
            if(Click==JOptionPane.YES_OPTION)
            try{
                int index[]=table.getSelectedRows();
                Statement s=DataCon.getDataCon().createStatement();
                for(int i=0;i<index.length;i++){
                    String id=""+table.getValueAt(index[i], 0);
                    s.execute("delete from tblproduct where proID="+id);
                }
                s.close();
                DefaultTableModel mod=(DefaultTableModel)table.getModel();
                for(int i=0;i<index.length;i++)
                mod.removeRow(index[i]-i);
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdDeleteActionPerformed
    
    private void callTableValues()throws Exception{
        Statement s=DataCon.getDataCon().createStatement();
        ResultSet r=s.executeQuery("select barcode,proName,suppliername,caNameEng,qty,upriceIn,upriceOut,status,createDate from vproduct");
        while(r.next()){
            String barcode=r.getString("barcode");
            String proname=r.getString("proName");
            String suname=r.getString("suppliername");
            String catename=r.getString("caNameEng");
            String qty=r.getString("qty");
            String upriceIn=r.getString("upriceIn");
            String upriceOut=r.getString("upriceOut");
            String status=r.getString("status");
            String cdate=r.getString("createDate");
            
            String st[]={barcode,proname,suname,catename,qty,upriceIn,upriceOut,status,cdate};
            table.addRow(st);
        }
        r.close();
        s.close();
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try{
            callTableValues();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void lbBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBackMouseClicked
        try{
            MainFrame.main(null);
            this.dispose();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_lbBackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewListPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewListPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewListPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewListPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewListPro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SSeting;
    private javax.swing.JPanel barHome;
    private javax.swing.JButton cmdDelete;
    private javax.swing.JButton cmdExit;
    private javax.swing.JButton cmdMax;
    private javax.swing.JButton cmdMin;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbBack;
    private javax.swing.JPanel pnlToolBar;
    private subjtable.SubJTable table;
    private subjtextfiledsk15.SubJTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
